// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmo7wIKDXZWapZGxWAEpnXd8NA8vansQ',
    appId: '1:900069822635:web:db1981ff54b616e0b327ee',
    messagingSenderId: '900069822635',
    projectId: 'stud-expense',
    authDomain: 'stud-expense.firebaseapp.com',
    storageBucket: 'stud-expense.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs22qFjbrB7xu6cwB_68f0GagivD98Iu8',
    appId: '1:900069822635:android:c4b8ce42b416a61db327ee',
    messagingSenderId: '900069822635',
    projectId: 'stud-expense',
    storageBucket: 'stud-expense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeIXzN_rWHF3BYJVtmXFULSRYQDr3wR4U',
    appId: '1:900069822635:ios:9306091deccadff8b327ee',
    messagingSenderId: '900069822635',
    projectId: 'stud-expense',
    storageBucket: 'stud-expense.firebasestorage.app',
    iosBundleId: 'com.example.studExpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeIXzN_rWHF3BYJVtmXFULSRYQDr3wR4U',
    appId: '1:900069822635:ios:9306091deccadff8b327ee',
    messagingSenderId: '900069822635',
    projectId: 'stud-expense',
    storageBucket: 'stud-expense.firebasestorage.app',
    iosBundleId: 'com.example.studExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFmo7wIKDXZWapZGxWAEpnXd8NA8vansQ',
    appId: '1:900069822635:web:0e3d2bc6b8a3de9eb327ee',
    messagingSenderId: '900069822635',
    projectId: 'stud-expense',
    authDomain: 'stud-expense.firebaseapp.com',
    storageBucket: 'stud-expense.firebasestorage.app',
  );
}
